language: node_js
sudo: false
node_js:
  - '4.0'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    secure: q2gNgw8IDzHO/+F6aXmgReEClaCzlRk8k6nPTrJ4rYeKcRZeQ3uBvaQX33x5dsVBWvgacrQTIGwQHDeV53moM8mb1xp9jo6cO8/I824Oom949XBtT6cx3Te7oCb2RRT1120QuHIAmlJjveydyLNwxNFs33Vwng3qlEa2keLUPZ1GXkm2Ab2hvpT3Hu2GX/XFXrMmZn9MlZPa+P8/Jz4INSv1Uhui0jPvv77xGmIy5qUmC+uaBAaR4rqRKEF8ApCBhRyRlYl7OVCxQb0JTdD9QvJYV9st331MW86VgnXQw0IvVvv5L9bwbDuh8EiqGlwUTrzrodhMdRT4hONhz30hBGsWKvxSo7EJu+R2RX9lvsiu0vw1wbZZ+EyX/FlzFL0N574vVGF1urA2PDQV/Cs++g7bj7pe0sPsp6wSMfXYBiB6H93UV4OF4zuyg2Z6/RxhTP0/BryaFYd5j3G99ctN8PrzRbWT4nB5tkVUTPZbOX7iA8/d86FV+V0MY4eCUfefv0ZdvNbc40JDRDLVeVFgOLmv12H9T9BmWsuZjf7irC+twmMopx5DamwMZzII9TKaQdx2FtA/OCNxfQg0ei/CUAyRqMs3NCOFqBINkRjG3n/STkH8nATL+bngY0ZQ1HOx4yNVSboGx2nWKNDcFRghXB8D3SQ/x9NiSFROXLTswbM=
